---
# Reference: https://specifications.freedesktop.org/basedir/latest/

# xdg_data_home defines the base directory relative to which user-specific
# data files should be stored.
xdg_data_home: "{{ ansible_user_dir }}/.local/share"

# xdg_config_home defines the base directory relative to which user-specific
# configuration files should be stored.
xdg_config_home: "{{ ansible_user_dir }}/.config"

# xdg_state_home defines the base directory relative to which user-specific
# state files should be stored.
xdg_state_home: "{{ ansible_user_dir }}/.local/state"

# xdg_cache_home defines the base directory relative to which user-specific
# non-essential data files should be stored.
xdg_cache_home: "{{ ansible_user_dir }}/.cache"
