---
- name: Add the default Go toolchain
  ansible.builtin.apt:
    name:
    - golang-go
    - go-bindata
  become: true

- name: Create GOPATH directory
  ansible.builtin.file:
    path: "{{ golang_path }}"
    state: directory

# Do not overwrite the file since GOROOT may have been
# manually changed to a different Go toolchain version.
- name: Add GOPATH and GOROOT environment variables
  ansible.builtin.template:
    src: golang.j2
    dest: "{{ bash_aliases_dir }}/golang"
    force: no

- name: Clone vim-go as a vim package
  ansible.builtin.git:
    repo: https://github.com/fatih/vim-go.git
    dest: "{{ ansible_user_dir }}/.vim/pack/plugins/start/vim-go"

- name: Install additional Go binaries to support vim-go
  ansible.builtin.command: vim -e "+GoInstallBinaries" "+q"
