---
- name: Get architecture of packages dpkg installs
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_result
  changed_when: false

- name: Set dpkg_architecture fact
  ansible.builtin.set_fact:
    dpkg_architecture: "{{ dpkg_result.stdout }}"
