---
- name: Begin autofs configuration
  become: yes
  block:

  - name: Add autofs and nfs-common packages
    apt:
      name:
      - autofs
      - nfs-common

  - name: Enable automatic host-based mounts
    lineinfile:
      path: /etc/auto.master
      regexp: '^#?(/net\s+-hosts)$'
      line: '\1'
      backrefs: true
    notify: Restart autofs
