---
- name: "{{ nginx_revproxy_name }} : Add nginx configuration"
  ansible.builtin.template:
    src: proxy.conf.j2
    dest: "{{ nginx_config_dir }}/nginx/site-confs/proxy-{{ nginx_revproxy_name }}.conf"
