---
- name: Limit journal disk usage
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUser="
    line: "SystemMaxUse={{ journal_max_disk_usage }}"
  become: yes
  notify: Restart journald
