---
- name: Install the latest Git Credential Manager release
  ansible.builtin.import_role:
    name: github_release
  vars:
    github_release_name: Git Credential Manager
    github_release_owner: git-ecosystem
    github_release_repo: git-credential-manager

- name: Add bash configuration
  ansible.builtin.copy:
    src: git-credential-manager
    dest: "{{ common_user_bash_aliases_dir }}/"
    mode: u=rw,g=rw,o=r
