---
- name: Begin LightDM configuration
  become: yes
  block:

  - name: Add lightdm and related packages
    ansible.builtin.apt:
      name:
      - lightdm
      - lightdm-gtk-greeter
      - light-locker

  - name: Tweak lightdm configuration
    ansible.builtin.lineinfile:
      path: /etc/lightdm/lightdm.conf
      regexp: "#?{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
    loop:
    - key: greeter-hide-users
      value: "false"
    when: ansible_distribution == "Debian"

- name: Give lightdm user access to user directory
  ansible.posix.acl:
    path: "{{ ansible_user_dir }}"
    entity: lightdm
    etype: user
    permissions: x
    state: present

- name: Download a face image for login screen
  ansible.builtin.get_url:
    url: "{{ lightdm_face_url }}"
    dest: "{{ ansible_user_dir }}/.face"
    force: true
