---
- name: Look up timezone name
  ansible.builtin.command: cat /etc/timezone
  register: timezone_result
  changed_when: False

- name: Set timezone fact
  ansible.builtin.set_fact:
    timezone: "{{ timezone_result.stdout }}"
