---
- name: Add jc package
  ansible.builtin.apt:
    name:
    - jc
  become: yes

- name: Run lsmod
  ansible.builtin.command: jc lsmod
  register: lsmod_result
  changed_when: False

- name: Set kernel_modules fact
  ansible.builtin.set_fact:
    kernel_modules: "{{ lsmod_result.stdout | from_json }}"
