---
- name: Install the latest Balena Etcher release
  ansible.builtin.import_role:
    name: github_release
  vars:
    github_release_name: Balena Etcher
    github_release_owner: balena-io
    github_release_repo: etcher
